#define HOMEPAGE "ddg.gg"
#define CASEFIND FALSE
#define SHOW_HSCROLL FALSE
#define SHOW_VSCROLL FALSE
#define SEARCH "duckduckgo.com/?q=%s"
#define STEP 44
#define ZOOM 0.8
#define WIDTH 640
#define HEIGHT 480
#define OWLDIR ".owl-browser"
#define COOKIEFILE "cookie"
#define USECOOKIE TRUE
